### ISSUE TITLE
国际版等级过滤

### ISSUE THREAD

**Issue by ccl1194** [Tile-X/BiCleaner#1]
国际版最新版等级过滤还是能看到

**Comment by MeowBug** [comment]
> 国际版最新版等级过滤还是能看到

是完全没有效果，还是部分评论没有被屏蔽，不确定的话可以开留痕看一下。

**Comment by ccl1194** [comment]
7750600
7024zygisk
4级过滤，仍然有二三级评论
留痕已经打开了，目前日志只显示xxxx

**Comment by MeowBug** [comment]
> 7750600 7024zygisk 4级过滤，仍然有二三级评论 留痕已经打开了，目前日志只显示xxxx

好的

**Comment by MeowBug** [comment]
> 7750600 7024zygisk 4级过滤，仍然有二三级评论 留痕已经打开了，目前日志只显示xxxx

你试一下新发布的版本，过滤应该可以起效了，可能会有几条漏掉，但大部分应该都会被过滤掉。

**Comment by ccl1194** [comment]
最新版测试过了，国内版8120200有效果，极个别评论会漏掉
国际版7750600没变化
hyperos 1.0.8.0 安卓14
日志功能暂不可用
如果继续修复的话，可以帮忙测试提供反馈

话说是不是因为最近2级垃圾号太多才开发这个😂

**Comment by MeowBug** [comment]
> 最新版测试过了，国内版8120200有效果，极个别评论会漏掉
> 国际版7750600没变化
> hyperos 1.0.8.0 安卓14
> 日志功能暂不可用
> 如果继续修复的话，可以帮忙测试提供反馈
> 
> 话说是不是因为最近2级垃圾号太多才开发这个😂
> 
> 

嘶，不应该啊。我这MIUI14哔哩哔哩国际版工作正常啊，目前虽然发现了两个评论接口，但走的都是MainReplyList的。我后续把日志功能完善，看看能不能得到其他的信息。

**Comment by ccl1194** [comment]
有没有可能是框架的问题 我的是1.9.3mod版
奇怪的地方就在于play版不生效 国内版可以用
有没有国内其他平台的账号 方便关注一下的
